let java = [];
let name;

function createJava(){
  name = prompt("File Name:", "Model");
  if(name != null && name != ""){
    java.push(
    "// Add package above"+
    "// Java generated by Minecraft Entity Modeler\n"+
    "// ~swimauger\n\n"+
    "import net.minecraft.client.model.ModelBase;\n"+
    "import net.minecraft.client.model.ModelRenderer;\n"+
    "import net.minecraft.entity.Entity;\n"+
    "import net.minecraft.util.math.MathHelper;\n\n"+
    "public class "+name+" extends ModelBase{\n"
    );
    for(let i=0;i < blockStack.length;i++){
      java.push("       ModelRenderer "+blockStack[i].name+";\n");
    }
    java.push(
    "\n\n   public "+name+"(){\n"+
    "       //textureWidth = "+"ADD_TEXTURE_WIDTH"+";\n"+
    "       //textureHeight = "+"ADD_TEXTURE_HEIGHT"+";\n\n"
    );
    for(let j=0;j < blockStack.length;j++){
      java.push(
      "       "+blockStack[j].name+" = new ModelRenderer(this, "+"0"+", "+"0"+");\n"+
      "       "+blockStack[j].name+".addBox("+(blockStack[j].length/-2)+"F, "+(blockStack[j].width/-2)+"F, "+(blockStack[j].height/-2)+"F, "+blockStack[j].length+", "+blockStack[j].width+", "+blockStack[j].height+");\n"+
      "       "+blockStack[j].name+".setRotationPoint("+blockStack[j].x+"F, "+blockStack[j].y*-1+"F, "+blockStack[j].z+"F);\n"+
      "       "+blockStack[j].name+".mirror = true;\n"+
      "       setRotation("+blockStack[j].name+", 0F, 0F, 0F);\n"
      );
    }
    java.push(
    "   }\n\n"+
    "   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5){\n"+
    "       super.render(entity, f, f1, f2, f3, f4, f5);\n"+
    "       setRotationAngles(f, f1, f2, f3, f4, f5, entity);\n"
    );
    for(let k=0;k < blockStack.length;k++){
      java.push(
      "       "+blockStack[k].name+".render(f5);\n"
      );
    }
    java.push(
    "   }\n\n"+
    "   private void setRotation(ModelRenderer model, float x, float y, float z){\n"+
    "       model.rotateAngleX = x;\n"+
    "       model.rotateAngleY = y;\n"+
    "       model.rotateAngleZ = z;\n"+
    "   }\n\n"+
    "   public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn){\n"+
    "   }\n\n"+
    "}"
    );
    createExport();
  }
}

function createExport(){
  let fileName = name+".java";
  var file = new File(java, fileName, {type: "text/plain;charset=utf-8"});
  java = [];
  saveAs(file);
}
